//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejemploMiercoles2.WsCategorias {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/WSCategorias")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsCategorias.ICategorias")]
    public interface ICategorias {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/getCategorias", ReplyAction="http://tempuri.org/ICategorias/getCategoriasResponse")]
        ejemploMiercoles2.WsCategorias.Categoria[] getCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/getCategorias", ReplyAction="http://tempuri.org/ICategorias/getCategoriasResponse")]
        System.Threading.Tasks.Task<ejemploMiercoles2.WsCategorias.Categoria[]> getCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/insertCategoria", ReplyAction="http://tempuri.org/ICategorias/insertCategoriaResponse")]
        bool insertCategoria(string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/insertCategoria", ReplyAction="http://tempuri.org/ICategorias/insertCategoriaResponse")]
        System.Threading.Tasks.Task<bool> insertCategoriaAsync(string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/updateCategoria", ReplyAction="http://tempuri.org/ICategorias/updateCategoriaResponse")]
        bool updateCategoria(int id, string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategorias/updateCategoria", ReplyAction="http://tempuri.org/ICategorias/updateCategoriaResponse")]
        System.Threading.Tasks.Task<bool> updateCategoriaAsync(int id, string nombre, string descripcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriasChannel : ejemploMiercoles2.WsCategorias.ICategorias, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriasClient : System.ServiceModel.ClientBase<ejemploMiercoles2.WsCategorias.ICategorias>, ejemploMiercoles2.WsCategorias.ICategorias {
        
        public CategoriasClient() {
        }
        
        public CategoriasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ejemploMiercoles2.WsCategorias.Categoria[] getCategorias() {
            return base.Channel.getCategorias();
        }
        
        public System.Threading.Tasks.Task<ejemploMiercoles2.WsCategorias.Categoria[]> getCategoriasAsync() {
            return base.Channel.getCategoriasAsync();
        }
        
        public bool insertCategoria(string nombre, string descripcion) {
            return base.Channel.insertCategoria(nombre, descripcion);
        }
        
        public System.Threading.Tasks.Task<bool> insertCategoriaAsync(string nombre, string descripcion) {
            return base.Channel.insertCategoriaAsync(nombre, descripcion);
        }
        
        public bool updateCategoria(int id, string nombre, string descripcion) {
            return base.Channel.updateCategoria(id, nombre, descripcion);
        }
        
        public System.Threading.Tasks.Task<bool> updateCategoriaAsync(int id, string nombre, string descripcion) {
            return base.Channel.updateCategoriaAsync(id, nombre, descripcion);
        }
    }
}
